---
- name: kubernetesplaybook
  hosts: all
  become: true
  tasks:
    - name: copy remote ansible machine
      copy:
       src: /var/lib/jenkins/workspace/computer/kpod.yaml
       dest: /home/ubuntu/
    
    - name: pod kubernetes
      shell:
        cmd: "kubectl apply -f kpod.yaml"
                               
