---
- name: kubernetesplaybook
  hosts: all
  become: true
  tasks:
    - name: copy dockerfile to remote ansible machine
      copy:
       src: /var/lib/jenkins/workspace/computer
       dest: /home/ubuntu/
       
    - name: copy pod yaml file to kubernetes
      copy:
        src: /home/ubuntu/kpod.yaml
        dest: /home/ubuntu/


    - name: pod kubernetes
      shell:
        cmd: "kubectl apply -f kpod.yaml"
                               
